"""
Send Email
----------
Reads output/latest-summary.md and sends it to thaperalta@gmail.com via SendGrid.
No Claude API needed — summary is generated by Claude Code via the /summarize-email skill.

Required env vars (see .env.example):
  SENDGRID_API_KEY, SENDGRID_FROM_EMAIL
"""

import os
from pathlib import Path
from datetime import datetime, timezone
import sendgrid
from sendgrid.helpers.mail import Mail
from dotenv import load_dotenv

load_dotenv()

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
SUMMARY_FILE      = Path(__file__).parent.parent / "output" / "latest-summary.md"
RECIPIENT_EMAIL   = "thaperalta@gmail.com"
SENDGRID_API_KEY  = os.environ["SENDGRID_API_KEY"]
FROM_EMAIL        = os.environ["SENDGRID_FROM_EMAIL"]


# ---------------------------------------------------------------------------
# Send email via SendGrid
# ---------------------------------------------------------------------------
def send_email(summary: str):
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    html  = summary.replace("\n", "<br>")

    email = Mail(
        from_email=FROM_EMAIL,
        to_emails=RECIPIENT_EMAIL,
        subject=f"[Opportunity Radar] Automation Plan Summary — {today}",
        html_content=html,
    )
    sg       = sendgrid.SendGridAPIClient(api_key=SENDGRID_API_KEY)
    response = sg.send(email)
    print(f"  Email sent to {RECIPIENT_EMAIL} — status: {response.status_code}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    if not SUMMARY_FILE.exists():
        raise FileNotFoundError(
            f"Summary file not found at {SUMMARY_FILE}. "
            "Run the /summarize-email skill in Cursor first."
        )

    print(f"Reading summary from {SUMMARY_FILE}...")
    summary = SUMMARY_FILE.read_text(encoding="utf-8")

    print(f"Sending email to {RECIPIENT_EMAIL}...")
    send_email(summary)
    print("Done.")


if __name__ == "__main__":
    main()
